title: http-assert-plus
description:
baseurl: /http-assert-plus
url: https://someimportantcompany.github.io
repository: someimportantcompany/http-assert-plus

header:
  title: http-assert-plus
  links:
    - label: View on Github
      url: https://github.com/someimportantcompany/http-assert-plus
      new: true

sidebar: false

footer:
  back-to-top:
    label: Back to top
  content: >-
    Copyright © 2023 <a href="https://someimportantcompany.github.io" target="_blank">Some Important Company</a>.
    <a href="https://github.com/someimportantcompany/http-assert-plus/blob/master/LICENSE" target="_blank">MIT License</a>.
  gh-edit-link:
    repository: someimportantcompany/http-assert-plus
    branch: master
    view: tree

remote_theme: someimportantcompany/jekyll-documentation
permalink: pretty
